spring.application.name=PraticaActualizacionJava

# Puerto de la app
server.port=8080

# Actuator — expone /actuator/health
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# S3 — se leerá de variables de entorno en EC2
aws.s3.bucket=${S3_BUCKET:mi-bucket-local}
aws.s3.region=${AWS_REGION:us-east-2}

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method